name: rig
version: "1"
date: 2014-05-24
description: |
    Racks in GAP

authors:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram

maintainers:
    - name: Leandro Vendramin
      url: http://mate.dm.uba.ar/~lvendram

GAP: ">=4.8"

www: https://gap-packages.github.io/rig/
readme: README.md
packageinfo: https://gap-packages.github.io/rig/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/rig/releases/download/v1/rig-1.tar.gz

abstract: |
    The <span class="pkgname">Example</span> package, as its name suggests,    is an example of how to create a <span class="pkgname">GAP</span>    package. It has little functionality except for being a package

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    racks, quandles, nichols algebras, knots.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ven14</span>]   <b class='BibAuthor'>Vendramin, L.</b>,
     <i class='BibTitle'>rig, Racks in GAP,
             Version 1</i>
     (<span class='BibYear'>2014</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/rig/">https://gap-packages.github.io/rig/</a></span>.
    </p>
    

bibtex: |
    @misc{ rig1,
      author =           {Vendramin, L.},
      title =            {{rig}, Racks in GAP, {V}ersion 1},
      month =            {May},
      year =             {2014},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/rig/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{rig/}}},
      keywords =         {racks; quandles; nichols algebras; knots},
      printedkey =       {Ven14}
    }

