ReadPackage("rig", "gap/basic.gi" );
ReadPackage("rig", "gap/subracks.gi" );
ReadPackage("rig", "gap/nichols.gi" );
ReadPackage("rig", "gap/homology.gi" );
ReadPackage("rig", "gap/utils.gi" );
ReadPackage("rig", "gap/braid.gi" );
ReadPackage("rig", "gap/polynomial.gi" );
#ReadPackage("rig", "small/small_racks_library.gi");
ReadPackage("rig", "small/small_quandles.gi");
ReadPackage("rig", "gap/extensions.gi");
