ReadPackage("rig", "gap/basic.gd");
ReadPackage("rig", "gap/subracks.gd");
ReadPackage("rig", "gap/nichols.gd");
ReadPackage("rig", "gap/utils.gd");
ReadPackage("rig", "gap/homology.gd");
ReadPackage("rig", "gap/polynomial.gd");
ReadPackage("rig", "gap/braid.gd");
#ReadPackage("rig", "small/small_racks_library.gd");
ReadPackage("rig", "small/small_quandles.gd");
